version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging into ECR..."
      - export REPO_URI=...
      - export BRANCH=...
      - export DATE=$(date +%y%m%d)
      - |
        COUNT=$(aws ecr describe-images \
          --repository-name $ECR_REPOSITORY_NAME \
          --filter tagStatus=TAGGED \
          --query "imageDetails[?starts_with(imageTags[0], \`${BRANCH}-${DATE}-\`)].imageTags[]" \
          --output text | wc -w)
        NEXT=$((COUNT + 1))
        IMAGE_TAG=$(printf "%03d" "$NEXT")
        export IMAGE_TAG_FULL="$BRANCH-$DATE-$IMAGE_TAG"
        echo "Tagging image: $IMAGE_TAG_FULL"
      - docker build -t $REPO_URI:latest .
      - docker tag $REPO_URI:latest $REPO_URI:$IMAGE_TAG_FULL
  post_build:
    commands:
      - docker push $REPO_URI:latest
      - docker push $REPO_URI:$IMAGE_TAG_FULL
      - echo "{\"imageUri\":\"$REPO_URI:$IMAGE_TAG_FULL\"}" > image-info.json
artifacts:
  files:
    - image-info.json
