phases:
  install:
    commands:
      - pip install git-remote-codecommit
  post_build:
    commands:
      - git clone codecommit://$AWS_REGION://report-service-cdk report
      - cd report
      - git checkout sit || git checkout -b sit
      - echo "{\"imageUri\":\"$REPO_URI:$IMAGE_TAG\"}" > image-info.json
      - git add image-info.json
      - git config user.email "ci-bot@myorg"
      - git config user.name "CI Bot"
      - git commit -m "Update imageUri" || echo "No changes"
      - git push origin sit
