env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - git config --global user.name "Build Bot"
      - git config --global user.email "build-bot@company.com"

  post_build:
    commands:
      - echo "Cloning report-service-cdk via HTTPS"
      - git clone https://git-codecommit.$AWS_DEFAULT_REGION.amazonaws.com/v1/repos/report-service-cdk report
